"""Security policy and guarded fetching support for remote documents."""

from .guarded_fetch import FetchResult, GuardedFetcher
from .remote_fetch import (
    BadRequestTarget,
    ConnectionInfo,
    DeadlineExceeded,
    DnsResolutionError,
    FetchReport,
    HopReport,
    HostBlocked,
    PolicyLimits,
    PolicyViolation,
    RateLimitExceeded,
    RedirectLimitExceeded,
    RemoteFetchError,
    RemoteFetchPolicy,
    SchemeBlocked,
    TransferLimitExceeded,
    UnixProxyBlocked,
    UnsupportedCharset,
    UnsupportedEncoding,
    classify_ip,
    normalize_host,
)

__all__ = [
    "BadRequestTarget",
    "ConnectionInfo",
    "DeadlineExceeded",
    "DnsResolutionError",
    "FetchReport",
    "FetchResult",
    "GuardedFetcher",
    "HopReport",
    "HostBlocked",
    "PolicyLimits",
    "PolicyViolation",
    "RateLimitExceeded",
    "RedirectLimitExceeded",
    "RemoteFetchError",
    "RemoteFetchPolicy",
    "SchemeBlocked",
    "TransferLimitExceeded",
    "UnixProxyBlocked",
    "UnsupportedCharset",
    "UnsupportedEncoding",
    "classify_ip",
    "normalize_host",
]
